title: ShokuAI
description: Aplikacja mobilna
show_downloads: false

baseurl: "/appTest.github.io" 
url: "https://paulinalewicka1.github.io"

github:
  pdf_url: "https://paulinalewicka1.github.io/appTest.github.io/instruction.pdf"
  apk_url: "https://paulinalewicka1.github.io/appTest.github.io/app-release.apk"
  prezentacja_url: "https://paulinalewicka1.github.io/appTest.github.io/prezentacja.pdf"

#theme: jekyll-theme-cayman-blog
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-target-blank
  - kramdown-parser-gfm

target-blank:
    rel: nofollow

header_page_refs: ['app', 'tutorial', 'contact']

markdown: kramdown
